version: '3.8'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    
    ports:
      - "27017:27017"
    command: ["mongod", "--port", "27017"]
    volumes:
      - './data:/data/db'

  flatbot.webapi:  
    image: ${DOCKER_REGISTRY-}flatbotwebapi
    build:
      context: .
      dockerfile: FlatBot.WebApi/Dockerfile
    ports:
      - "80"
      - "443"
    depends_on:
      - mongo
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    links:
      - mongo
