version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    ports:
      - "27017:27017"

  web:
    build: .

    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "8080:80"
      # - "5001:80"
      - "8081:443"

    depends_on:
      - mongo
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
      # - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      # - ${HOME}/.aspnet/https:/root/.aspnet/https/
    links:
      - mongo
