version: '3.8'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: MSSQL_WebApi
    ports:
        - 1433:1433
    volumes:             
        - ./init:/docker-entrypoint-initdb.d
    environment:
        SA_PASSWORD: "Top.ptf05"
        ACCEPT_EULA: "Y"

  flatbot.webapi:  
    image: ${DOCKER_REGISTRY-}flatbotwebapi
    build:
      context: .
      dockerfile: FlatBot.WebApi/Dockerfile
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "80"
      # - "5001:80"
      - "443"
    depends_on:
      - mssql
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
      # - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      # - ${HOME}/.aspnet/https:/root/.aspnet/https/
    links:
      - mssql
