version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always

    ports:
      - "27017:27017"
    command: ["mongod", "--port", "27017"]
  flatbot.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - mongo
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https
    links:
      - mongo
